# Generated by Django 5.2.7 on 2025-10-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_chatsession_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-pinned', '-updated_at']},
        ),
        migrations.AddField(
            model_name='chatsession',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
