# Generated by Django 5.2.7 on 2025-10-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_chatsession_options_chatsession_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
