# Generated by Django 5.2.7 on 2025-10-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chatsession_profile_picture_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
