# Generated by Django 5.2.7 on 2025-10-09 17:12

from django.db import migrations
import os

def create_superuser(apps, schema_editor):
    User = apps.get_model('api', 'User')

    username = os.environ.get('DJANGO_SUPERUSER_USERNAME')
    email = os.environ.get('DJANGO_SUPERUSER_EMAIL')
    password = os.environ.get('DJANGO_SUPERUSER_PASSWORD')

    # Yeh check karta hai ki kya Render par secrets set hain
    if username and email and password:
        # Yeh check karta hai ki user pehle se exist toh nahi karta
        if not User.objects.filter(username=username).exists():
            print(f"Creating superuser: {username}")
            User.objects.create_superuser(username=username, email=email, password=password)
        else:
            print(f"Superuser '{username}' already exists.")



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_chatsession_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
